In [1]:
import pandas as pd
import numpy as np

In [37]:
df = pd.read_csv('survey_data_gender-equality-geosciences_2018_incl-career-stages.csv', delimiter=";")

In [38]:
df.head()

,Timestamp,What gender do you identify yourself with,What is your career stage,Do you work full-time,Which geographical background do you identify yourself with,Where are you currently based,Which scientific discipline do you primarily associate with,Do you know of the leaky pipeline in academia,Is the number of female to male early-career scientists approximately even in your department,Is the number of female to male tenured scientists approximately even in your department,...,Do you discuss gender bias/imbalance with your peers,"At your institution, are there any activities and/or training programmes to improve/maintain gender balance","At your institution, are there any training, coaching or mentoring programs specifically targeted at women and/or men","If you have participated in such programs, how would you rate their usefulness to your career",Are role models important for your career choices,Do you have any gender preferences in selecting your role models,How important are family-related working conditions of your institution to you,do you support gender quotas for academic positions,do you support gender quotas for scientific awards,do you support gender quotas in the peer-review process
0,4.1.2018 10:25:44,Female,PhD student,Yes,Europe,Europe,Earth and Space Science Informatics,No,"Yes, the number of female to male scientists i...","No, there are more men than women",...,"Yes, regardless of their gender",No,No,Very useful,Very important,"Yes, same gender",Important in the future,2,2,2
1,3.26.2018 20:01:23,Male,"10 years as postdoc and lecturer, now guest le...",Yes,Europe,Europe,Geosciences Instrumentation and Data Systems,Yes,"Yes, the number of female to male scientists i...","No, there are more men than women",...,"No, I never discussed the topic",Yes,"Yes, at women",Not participated,Not important,No preference,Important at the moment,3,2,1
2,3.25.2018 17:06:22,Female,Assistant Professor / lecturer (or equivalent),Yes,Europe,Europe,"Stratigraphy, Sedimentology & Palaeontology",Yes,"Yes, the number of female to male scientists i...","No, there are more men than women",...,"Yes, regardless of their gender",Yes,No,Not participated,Not very important,No preference,Important in the future,4,4,4
3,3.25.2018 17:14:23,Female,Assistant Professor / lecturer (or equivalent),Yes,Europe,Europe,"Geochemistry, Mineralogy, Petrology & Volcanology",Yes,"Yes, the number of female to male scientists i...","No, there are more men than women",...,"Yes, regardless of their gender",Yes,"Yes, at women and men",Very useful,Very important,No preference,Important in the future,1,1,1
4,3.25.2018 20:30:41,Female,Assistant Professor / lecturer (or equivalent),"No, part-time",Europe,Europe,Hydrological Sciences,Yes,"Yes, the number of female to male scientists i...","No, there are more men than women",...,"Yes, regardless of their gender",Yes,"Yes, at women",Not very useful,Not important,"Yes, same gender",Important at the moment,5,5,1

In [4]:
for column_name in df.columns:
    print(column_name)

Timestamp
What gender do you identify yourself with
What is your career stage
Do you work full-time
Which geographical background do you identify yourself with
Where are you currently based
Which scientific discipline do you primarily associate with
Do you know of the leaky pipeline in academia
Is the number of female to male early-career scientists approximately even in your department
Is the number of female to male tenured scientists approximately even in your department
Does gender imbalance affect your experience or behaviour when attending a scientific meeting
Do you consider an equal gender distribution in a research/project group an important factor for creating a healthy working atmosphere
Do you feel like you have been subjected to gender bias in your own institution
Do you feel like you have been subjected to gender bias in scientific organizations
How much are your interactions with female scientists influenced by gender bias
How much are your interactions with male scientists influenced by gender bias
how gender-biased do you consider female scientists at your institution
how gender-biased do you consider male scientists at your institution
Do you discuss gender bias/imbalance with your peers
At your institution, are there any activities and/or training programmes to improve/maintain gender balance
At your institution, are there any training, coaching or mentoring programs specifically targeted at women and/or men
If you have participated in such programs, how would you rate their usefulness to your career
Are role models important for your career choices
Do you have any gender preferences in selecting your role models
How important are family-related working conditions of your institution to you
do you support gender quotas for academic positions
do you support gender quotas for scientific awards
do you support gender quotas in the peer-review process

In [5]:
df.rename(columns={'What gender do you identify yourself with': 'gender', 
                   'What is your career stage': 'career_stage',
                  'Do you work full-time' : 'employent_type',
                  'Which geographical background do you identify yourself with' : 'background',
                  'Where are you currently based' : 'current_location',
                  'Which scientific discipline do you primarily associate with' : 'discipline',
                  'Do you know of the leaky pipeline in academia ' : 'leaky_pipeline',
                  'Is the number of female to male early-career scientists approximately even in your department' : 'early_career_mumber',
                  'Is the number of female to male tenured scientists approximately even in your department' : 'tenured_number',
                  'Does gender imbalance affect your experience or behaviour when attending a scientific meeting' : 'gender_imb_exp',
                  'Do you consider an equal gender distribution in a research/project group an important factor for creating a healthy working atmosphere' : 'gender_distr_imp',
                  'Do you feel like you have been subjected to gender bias in your own institution' : 'gender_bias_institution',
                  'Do you feel like you have been subjected to gender bias in scientific organizations' : 'gender_bias_org',
                  'How much are your interactions with female scientists influenced by gender bias' : 'f_interactions_gender_bias',
                  'How much are your interactions with male scientists influenced by gender bias ' : 'm_interactions_gender_bias',
                  'how gender-biased do you consider female scientists at your institution' : 'f_gender_biased',
                  'how gender-biased do you consider male scientists at your institution' : 'm_gender_biased',
                  'Do you discuss gender bias/imbalance with your peers' : 'discuss_bias',
                  'At your institution, are there any activities and/or training programmes to improve/maintain gender balance' : 'training',
                  'At your institution, are there any training, coaching or mentoring programs specifically targeted at women and/or men' : 'target_programs',
                  'If you have participated in such programs, how would you rate their usefulness to your career ' : 'usefulness_rating',
                  'Are role models important for your career choices' : 'importance_role_models',
                  'Do you have any gender preferences in selecting your role models' : 'role_models_gender',
                  'How important are family-related working conditions of your institution to you' : 'family',
                  'do you support gender quotas for academic positions' : 'g_q_academic_positions',
                  'do you support gender quotas for scientific awards' : 'g_q_awards',
                  'do you support gender quotas in the peer-review process' : 'g_q_peer_review'}, inplace=True)

In [6]:
for column_name in df.columns:
    print(column_name)

Timestamp
gender
career_stage
employent_type
background
current_location
discipline
leaky_pipeline
early_career_mumber
tenured_number
gender_imb_exp
gender_distr_imp
gender_bias_institution
gender_bias_org
f_interactions_gender_bias
m_interactions_gender_bias
f_gender_biased
m_gender_biased
discuss_bias
training
target_programs
usefulness_rating
importance_role_models
role_models_gender
family
g_q_academic_positions
g_q_awards
g_q_peer_review

In [7]:
df.shape

(1220, 28)

In [8]:
df.dtypes

Timestamp                     object
gender                        object
career_stage                  object
employent_type                object
background                    object
current_location              object
discipline                    object
leaky_pipeline                object
early_career_mumber           object
tenured_number                object
gender_imb_exp                object
gender_distr_imp              object
gender_bias_institution       object
gender_bias_org               object
f_interactions_gender_bias     int64
m_interactions_gender_bias     int64
f_gender_biased                int64
m_gender_biased                int64
discuss_bias                  object
training                      object
target_programs               object
usefulness_rating             object
importance_role_models        object
role_models_gender            object
family                        object
g_q_academic_positions         int64
g_q_awards                     int64
g_q_peer_review                int64
dtype: object

In [9]:
obj_df = df.select_dtypes(include=['object']).copy()
obj_df.head()

,Timestamp,gender,career_stage,employent_type,background,current_location,discipline,leaky_pipeline,early_career_mumber,tenured_number,...,gender_distr_imp,gender_bias_institution,gender_bias_org,discuss_bias,training,target_programs,usefulness_rating,importance_role_models,role_models_gender,family
0,4.1.2018 10:25:44,Female,PhD student,Yes,Europe,Europe,Earth and Space Science Informatics,No,"Yes, the number of female to male scientists i...","No, there are more men than women",...,"Yes, to some extent","Yes, both to my advantage and disadvantage","Yes, mostly to my disadvantage","Yes, regardless of their gender",No,No,Very useful,Very important,"Yes, same gender",Important in the future
1,3.26.2018 20:01:23,Male,"10 years as postdoc and lecturer, now guest le...",Yes,Europe,Europe,Geosciences Instrumentation and Data Systems,Yes,"Yes, the number of female to male scientists i...","No, there are more men than women",...,"Yes, to some extent",No,No,"No, I never discussed the topic",Yes,"Yes, at women",Not participated,Not important,No preference,Important at the moment
2,3.25.2018 17:06:22,Female,Assistant Professor / lecturer (or equivalent),Yes,Europe,Europe,"Stratigraphy, Sedimentology & Palaeontology",Yes,"Yes, the number of female to male scientists i...","No, there are more men than women",...,"Yes, to some extent","Yes, mostly to my advantage","Yes, mostly to my advantage","Yes, regardless of their gender",Yes,No,Not participated,Not very important,No preference,Important in the future
3,3.25.2018 17:14:23,Female,Assistant Professor / lecturer (or equivalent),Yes,Europe,Europe,"Geochemistry, Mineralogy, Petrology & Volcanology",Yes,"Yes, the number of female to male scientists i...","No, there are more men than women",...,Yes,"Yes, both to my advantage and disadvantage","Yes, mostly to my disadvantage","Yes, regardless of their gender",Yes,"Yes, at women and men",Very useful,Very important,No preference,Important in the future
4,3.25.2018 20:30:41,Female,Assistant Professor / lecturer (or equivalent),"No, part-time",Europe,Europe,Hydrological Sciences,Yes,"Yes, the number of female to male scientists i...","No, there are more men than women",...,Yes,"Yes, both to my advantage and disadvantage",No,"Yes, regardless of their gender",Yes,"Yes, at women",Not very useful,Not important,"Yes, same gender",Important at the moment

In [10]:
obj_df = obj_df.fillna({"usefulness_rating": 'missing'})

In [11]:
obj_df = obj_df.fillna({"background": 'missing'})

In [12]:
obj_df.isnull().sum()

Timestamp                  0
gender                     0
career_stage               0
employent_type             0
background                 0
current_location           0
discipline                 0
leaky_pipeline             0
early_career_mumber        0
tenured_number             0
gender_imb_exp             0
gender_distr_imp           0
gender_bias_institution    0
gender_bias_org            0
discuss_bias               0
training                   0
target_programs            0
usefulness_rating          0
importance_role_models     0
role_models_gender         0
family                     0
dtype: int64

In [13]:
obj_df["gender"].value_counts()

Female    818
Male      402
Name: gender, dtype: int64

In [14]:
clean_gender = {"gender": {"Female": 1, "Male": 2}}

In [15]:
obj_df = obj_df.replace(clean_gender)

In [16]:
obj_df["employent_type"].value_counts()

Yes              975
No, part-time    245
Name: employent_type, dtype: int64

In [17]:
clean_employment = {"employent_type": {"Yes": 1, "No, part-time": 2}}
obj_df = obj_df.replace(clean_employment)
obj_df.head()

,Timestamp,gender,career_stage,employent_type,background,current_location,discipline,leaky_pipeline,early_career_mumber,tenured_number,...,gender_distr_imp,gender_bias_institution,gender_bias_org,discuss_bias,training,target_programs,usefulness_rating,importance_role_models,role_models_gender,family
0,4.1.2018 10:25:44,1,PhD student,1,Europe,Europe,Earth and Space Science Informatics,No,"Yes, the number of female to male scientists i...","No, there are more men than women",...,"Yes, to some extent","Yes, both to my advantage and disadvantage","Yes, mostly to my disadvantage","Yes, regardless of their gender",No,No,Very useful,Very important,"Yes, same gender",Important in the future
1,3.26.2018 20:01:23,2,"10 years as postdoc and lecturer, now guest le...",1,Europe,Europe,Geosciences Instrumentation and Data Systems,Yes,"Yes, the number of female to male scientists i...","No, there are more men than women",...,"Yes, to some extent",No,No,"No, I never discussed the topic",Yes,"Yes, at women",Not participated,Not important,No preference,Important at the moment
2,3.25.2018 17:06:22,1,Assistant Professor / lecturer (or equivalent),1,Europe,Europe,"Stratigraphy, Sedimentology & Palaeontology",Yes,"Yes, the number of female to male scientists i...","No, there are more men than women",...,"Yes, to some extent","Yes, mostly to my advantage","Yes, mostly to my advantage","Yes, regardless of their gender",Yes,No,Not participated,Not very important,No preference,Important in the future
3,3.25.2018 17:14:23,1,Assistant Professor / lecturer (or equivalent),1,Europe,Europe,"Geochemistry, Mineralogy, Petrology & Volcanology",Yes,"Yes, the number of female to male scientists i...","No, there are more men than women",...,Yes,"Yes, both to my advantage and disadvantage","Yes, mostly to my disadvantage","Yes, regardless of their gender",Yes,"Yes, at women and men",Very useful,Very important,No preference,Important in the future
4,3.25.2018 20:30:41,1,Assistant Professor / lecturer (or equivalent),2,Europe,Europe,Hydrological Sciences,Yes,"Yes, the number of female to male scientists i...","No, there are more men than women",...,Yes,"Yes, both to my advantage and disadvantage",No,"Yes, regardless of their gender",Yes,"Yes, at women",Not very useful,Not important,"Yes, same gender",Important at the moment

In [18]:
for column_name in obj_df.columns:
    print(obj_df[column_name].value_counts())

3.28.2018 10:53:43    1
3.31.2018 14:33:00    1
3.25.2018 16:26:45    1
3.27.2018 14:32:40    1
3.31.2018 2:38:30     1
                     ..
3.27.2018 13:43:29    1
3.27.2018 19:12:36    1
3.29.2018 14:40:12    1
3.27.2018 14:40:02    1
3.28.2018 17:18:18    1
Name: Timestamp, Length: 1220, dtype: int64
1    818
2    402
Name: gender, dtype: int64
PhD student                                                                    427
Post-Doc                                                                       232
B.Sc. or M.Sc. student                                                         118
Non-tenured academic / scientist                                               118
Associate Professor (or equivalent)                                            106
Assistant Professor / lecturer (or equivalent)                                 105
Professor                                                                       92
10 years as postdoc and lecturer, now guest lecturer with a job in industry      1
Software engineer in research lab                                                1
Prof. Emeritus                                                                   1
retired                                                                          1
research assistant                                                               1
Wissenschaftliche Referentin                                                     1
Researcher (permanent position)                                                  1
Research Associate                                                               1
tenured academic / scientist                                                     1
University staff engineer                                                        1
semi-retired                                                                     1
Research support                                                                 1
Sessional lecturer                                                               1
Government research scientist, adjunct assistant professor                       1
Museum admin @ university campus                                                 1
Recently graduated masters student, working seasonal/temp positions              1
Research staff                                                                   1
Emeritus                                                                         1
Retired, Emeritus                                                                1
I am a PhD student and a retired outside academia Chartered level.               1
Emerita                                                                          1
 PhD student                                                                     1
Name: career_stage, dtype: int64
1    975
2    245
Name: employent_type, dtype: int64
Europe           656
North America    389
Asia              79
South America     54
Oceania           26
Africa            12
missing            4
Name: background, dtype: int64
Europe           651
North America    450
Oceania           42
Asia              36
South America     31
Africa            10
Name: current_location, dtype: int64
Hydrological Sciences                                293
Geomorphology                                        108
Geochemistry, Mineralogy, Petrology & Volcanology    105
Biogeosciences                                        92
Planetary and Solar System Sciences                   85
                                                    ...
Meteorology & hydrology                                1
Hydrogeological Sciences                               1
Systematic biology                                     1
Geoscience education                                   1
Astrobiology                                           1
Name: discipline, Length: 67, dtype: int64
Yes    842
No     378
Name: leaky_pipeline, dtype: int64
No, there are more men than women                             508
Yes, the number of female to male scientists is about even    471
Dont know                                                     121
No, there are more women than men                             120
Name: early_career_mumber, dtype: int64
No, there are more men than women                             997
Yes, the number of female to male scientists is about even    112
Dont know                                                      72
No, there are more women than men                              39
Name: tenured_number, dtype: int64
Yes, to some extent    411
No, not really         340
No, not at all         207
Yes                    164
Dont know               98
Name: gender_imb_exp, dtype: int64
Yes, to some extent    525
Yes                    481
No, not really         149
No, not at all          51
Dont know               14
Name: gender_distr_imp, dtype: int64
No                                            583
Yes, both to my advantage and disadvantage    262
Yes, mostly to my disadvantage                249
Dont know                                      63
Yes, mostly to my advantage                    63
Name: gender_bias_institution, dtype: int64
No                                            623
Dont know                                     251
Yes, mostly to my disadvantage                164
Yes, both to my advantage and disadvantage    131
Yes, mostly to my advantage                    51
Name: gender_bias_org, dtype: int64
Yes, regardless of their gender           775
Yes, but primarily with same-sex peers    255
No, I never discussed the topic           122
No, I avoid these discussions              68
Name: discuss_bias, dtype: int64
Yes          551
Dont know    375
No           294
Name: training, dtype: int64
Yes, at women            410
Dont know                345
No                       301
Yes, at women and men    162
Yes, at men                2
Name: target_programs, dtype: int64
Not participated    828
Somewhat useful     170
Very useful          78
Not very useful      60
missing              56
Not useful           28
Name: usefulness_rating, dtype: int64
Somewhat important    478
Very important        456
Not very important    126
Not important         121
Dont know              39
Name: importance_role_models, dtype: int64
No preference        775
Yes, same gender     330
Not applicable        85
Yes, other gender     30
Name: role_models_gender, dtype: int64
Important in the future    565
Important at the moment    363
Not very important         122
Not important              112
Dont know                   58
Name: family, dtype: int64

In [19]:
clean_discuss = {"importance_role_models": {"Dont know" : 5, "Very important": 4, "Somewhat important": 3, "Not very important": 2, 'Not important' : 1},
                "role_models_gender":{"No preference" : 1, "Yes, same gender" : 2, "Yes, other gender" : 3, "Not applicable" : -997},
                "family" :{"Not important" : 1, "Not very important" : 2, "Important at the moment" : 3, "Important in the future" : 4, "Dont know" : 5}}
obj_df = obj_df.replace(clean_discuss)

In [20]:
clean_training = {"training": {"Yes": 3, "Dont know": 2, 'No' : 1},
                 "target_programs": {"No" : 1, "Yes, at men" : 2, "Yes, at women" : 3, "Yes, at women and men" : 4, "Dont know" : 5},
                                    "usefulness_rating" :{"Not useful" : 1, "Not very useful" : 2, "Somewhat useful" : 3, 
                                                         "Very useful" : 4, "Not participated": 5, "missing" : -999}}
obj_df = obj_df.replace(clean_training)

In [21]:
clean_discuss = {"discuss_bias": {"Yes, regardless of their gender": 4, "Yes, but primarily with same-sex peers": 3, "No, I avoid these discussions": 2, 'No, I never discussed the topic' : 1}}
obj_df = obj_df.replace(clean_discuss)

In [22]:
clean_gender_imb = {"gender_bias_institution": {"Dont know" : 5, "Yes, both to my advantage and disadvantage": 4, "Yes, mostly to my disadvantage": 3, "Yes, mostly to my advantage": 2, 'No' : 1},
                   "gender_bias_org" : {"Dont know" : 5, "Yes, both to my advantage and disadvantage": 4, "Yes, mostly to my disadvantage": 3, "Yes, mostly to my advantage": 2, 'No' : 1}}
obj_df = obj_df.replace(clean_gender_imb)

In [23]:
clean_gender_imb = {"gender_imb_exp": {"Dont know": 5, "Yes": 4, "Yes, to some extent": 3, "No, not really": 2, 'No, not at all' : 1},
                   "gender_distr_imp" : {"Dont know": 5, "Yes": 4, "Yes, to some extent": 3, "No, not really": 2, 'No, not at all' : 1}}
obj_df = obj_df.replace(clean_gender_imb)

In [24]:
clean_numbers = {"early_career_mumber": {"No, there are more men than women": 1, "Yes, the number of female to male scientists is about even": 2,
                                           'Dont know' : 3, 'No, there are more women than men' : 4},
                   "tenured_number": {"No, there are more men than women": 1, "Yes, the number of female to male scientists is about even": 2,
                                           'Dont know' : 3, 'No, there are more women than men' : 4}}
obj_df = obj_df.replace(clean_numbers)

In [25]:
clean_l_p = {"leaky_pipeline": {"Yes": 1, "No": 0}}
obj_df = obj_df.replace(clean_l_p)

In [26]:
obj_df['dum_background'] = obj_df['background']
obj_df = pd.get_dummies(obj_df, columns=["dum_background"])

In [27]:
obj_df['dum_current_location'] = obj_df['current_location']
obj_df = pd.get_dummies(obj_df, columns=["dum_current_location"])

In [28]:
obj_df.head()

,Timestamp,gender,career_stage,employent_type,background,current_location,discipline,leaky_pipeline,early_career_mumber,tenured_number,...,dum_background_North America,dum_background_Oceania,dum_background_South America,dum_background_missing,dum_current_location_Africa,dum_current_location_Asia,dum_current_location_Europe,dum_current_location_North America,dum_current_location_Oceania,dum_current_location_South America
0,4.1.2018 10:25:44,1,PhD student,1,Europe,Europe,Earth and Space Science Informatics,0,2,1,...,0,0,0,0,0,0,1,0,0,0
1,3.26.2018 20:01:23,2,"10 years as postdoc and lecturer, now guest le...",1,Europe,Europe,Geosciences Instrumentation and Data Systems,1,2,1,...,0,0,0,0,0,0,1,0,0,0
2,3.25.2018 17:06:22,1,Assistant Professor / lecturer (or equivalent),1,Europe,Europe,"Stratigraphy, Sedimentology & Palaeontology",1,2,1,...,0,0,0,0,0,0,1,0,0,0
3,3.25.2018 17:14:23,1,Assistant Professor / lecturer (or equivalent),1,Europe,Europe,"Geochemistry, Mineralogy, Petrology & Volcanology",1,2,1,...,0,0,0,0,0,0,1,0,0,0
4,3.25.2018 20:30:41,1,Assistant Professor / lecturer (or equivalent),2,Europe,Europe,Hydrological Sciences,1,2,1,...,0,0,0,0,0,0,1,0,0,0

In [29]:
int_df = df.select_dtypes(include=['int64']).copy()
int_df.head()

,f_interactions_gender_bias,m_interactions_gender_bias,f_gender_biased,m_gender_biased,g_q_academic_positions,g_q_awards,g_q_peer_review
0,4,2,2,2,2,2,2
1,1,1,1,1,3,2,1
2,1,1,3,2,4,4,4
3,4,3,4,1,1,1,1
4,1,1,2,4,5,5,1

In [30]:
#obj_df = obj_df.join(pd.DataFrame(int_df.toarray(), columns=oe_style.categories_))

In [31]:
type(obj_df)

pandas.core.frame.DataFrame

In [32]:
clean_employment = {"career_stage": {"B.Sc. or M.Sc. student": 1, 
                                     "Recently graduated masters student, working seasonal/temp positions": 2,
                                    "PhD student": 2, " PhD student": 2, 
                                     "I am a PhD student and a retired outside academia Chartered level.": 2,
                                    "Post-Doc":3, "Research staff":3, "research assistant": 3, 
                                     "Research support": 3,
                                    "Non-tenured academic / scientist":4, "Sessional lecturer ": 4, 
                                     "Research Associate": 4,
                                    "Assistant Professor / lecturer (or equivalent)": 5, 
                                    "Government research scientist, adjunct assistant professor" : 5,
                                    "Associate Professor (or equivalent)": 6,
                                     "Researcher (permanent position) ": 6,
                                     "tenured academic / scientist": 6,
                                    "Professor": 7,
                                    "Emerita": 8, "Emeritus": 8, "Prof. Emeritus":8, "retired": 8, 
                                     "Retired, Emeritus": 8, "semi-retired": 8,
                                    "Museum admin @ university campus":9, 
                                     "University staff engineer":9, "Software engineer in research lab": 9,
                                    "Wissenschaftliche Referentin": 9, 
                                    "10 years as postdoc and lecturer, now guest lecturer with a job in industry": 9,
                                    }}

In [33]:
obj_df = obj_df.replace(clean_employment)

In [34]:
result = pd.concat([obj_df, int_df], axis=1)

In [35]:
result.head()

,Timestamp,gender,career_stage,employent_type,background,current_location,discipline,leaky_pipeline,early_career_mumber,tenured_number,...,dum_current_location_North America,dum_current_location_Oceania,dum_current_location_South America,f_interactions_gender_bias,m_interactions_gender_bias,f_gender_biased,m_gender_biased,g_q_academic_positions,g_q_awards,g_q_peer_review
0,4.1.2018 10:25:44,1,2,1,Europe,Europe,Earth and Space Science Informatics,0,2,1,...,0,0,0,4,2,2,2,2,2,2
1,3.26.2018 20:01:23,2,9,1,Europe,Europe,Geosciences Instrumentation and Data Systems,1,2,1,...,0,0,0,1,1,1,1,3,2,1
2,3.25.2018 17:06:22,1,5,1,Europe,Europe,"Stratigraphy, Sedimentology & Palaeontology",1,2,1,...,0,0,0,1,1,3,2,4,4,4
3,3.25.2018 17:14:23,1,5,1,Europe,Europe,"Geochemistry, Mineralogy, Petrology & Volcanology",1,2,1,...,0,0,0,4,3,4,1,1,1,1
4,3.25.2018 20:30:41,1,5,2,Europe,Europe,Hydrological Sciences,1,2,1,...,0,0,0,1,1,2,4,5,5,1

In [36]:
result.to_excel('sexist_survey_num_3.xlsx')